apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-test4-13hj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-test4-13hj
    app.kubernetes.io/part-of: my-test4-2
  name: my-test4-13hj4lxr
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: my-test4-13hj
    weight: 100
status: {}
