apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-test4-13hj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-test4-13hj
    app.kubernetes.io/part-of: my-test4-2
  name: my-test4-13hj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-test4-13hj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: my-test4-13hj
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mkosiarc-tenant/my-test4-2/my-test4-13hj@sha256:980d53128e937a1e751ab05e5bfc2ffab07dcea5f175cfe9795db023dbf7afe8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
